### ISSUE TITLE
A way to make things unique

### ISSUE THREAD

**Issue by SynergyEvolved** [unlight/prisma-nestjs-graphql#77]
Hi there! I have a bit of a strange problem.  I am using Apollo Federation and have 8 subgraphs and a gateway.  

Somehow NestJS is adding extra types to the generated schema.

To update the graphql gateway there must not be any duplicate type names in any of the graphs.  Somehow 5 of my graphs have 
this in their schema.

```
input StringFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  mode: QueryMode
  not: NestedStringFilter
}
```
This results in the following error:
```
WARN: The following build errors occurred:
Encountered 1 build error while trying to build the supergraph.
UNKNOWN: There can be only one type named "StringFilter".
```

Is there a way to prefix StringFilter to make it unique?

**Comment by unlight** [comment]
Generator was not designed to work in federated graphql.
Since `StringFilter` is generic scalar type filter, you can try to move it to gateway service and remove from others.

My first thought is to add is `isAbstract: true` in `@InputType()` decorator for other services, enable `combineScalarFilters`.
But currently it is not possible via config.

**Comment by SynergyEvolved** [comment]
Hi Unlight,

What I ended up doing is just keeping the generated files that I needed (*.model.ts, *enum.ts, *count.output.ts, *create-many*.input.ts), deleted the rest and used cti to generate a new index.ts.

Worked like a charm :)
